//undefconf.h


/*
 * MStar Platform Configuration
 */

#define SONGGO  1

#if 0
#ifndef CONFIG_MSTAR_NONE
  #define CONFIG_MSTAR_NONE 0
#endif

#ifndef CONFIG_MSTAR_TITANIA
  #define CONFIG_MSTAR_TITANIA 0
#endif

#ifndef CONFIG_MSTAR_TRITON
  #define CONFIG_MSTAR_TRITON 0
#endif

#ifndef CONFIG_MSTAR_TITANIA2
  #define CONFIG_MSTAR_TITANIA2 0
#endif

#ifndef CONFIG_MSTAR_CHIP_TYPE
  #define CONFIG_MSTAR_CHIP_TYPE 0
#endif

#ifndef CONFIG_MSTAR_TITANIA2
  #define CONFIG_MSTAR_TITANIA2 0
#endif

#ifndef CONFIG_Triton
  #define CONFIG_Triton 0
#endif



#ifndef CONFIG_MSTAR_TITANIA_BD_T2_CUS03_VBRD_BOARD_DVB_1
  #define CONFIG_MSTAR_TITANIA_BD_T2_CUS03_VBRD_BOARD_DVB_1 0
#endif

#ifndef CONFIG_MSTAR_TITANIA_BD_T2_CUS03_MBRD_BOARD_ATSC_1
  #define CONFIG_MSTAR_TITANIA_BD_T2_CUS03_MBRD_BOARD_ATSC_1 0
#endif

#ifndef CONFIG_MSTAR_TITANIA_BD_T2_CUS03_MBRD_BOARD_DVB_1
  #define CONFIG_MSTAR_TITANIA_BD_T2_CUS03_MBRD_BOARD_DVB_1 0
#endif

#ifndef CONFIG_MSTAR_TITANIA_BD_T2_CUS03_MIBRD_BOARD_ATSC_1
  #define CONFIG_MSTAR_TITANIA_BD_T2_CUS03_MIBRD_BOARD_ATSC_1 0
#endif

#ifndef CONFIG_MSTAR_TITANIA_BD_T2_CUS03_MINERAVA_BOARD_ATSC_1
  #define CONFIG_MSTAR_TITANIA_BD_T2_CUS03_MINERAVA_BOARD_ATSC_1 0
#endif

#ifndef CONFIG_MSTAR_TITANIA_BD_S5_CUS03_DEMO_BOARD_1
  #define CONFIG_MSTAR_TITANIA_BD_S5_CUS03_DEMO_BOARD_1 0
#endif

#ifndef CONFIG_MSTAR_TITANIA_BD_S6_CUS03_DEMO_BOARD_ATSC_1
  #define CONFIG_MSTAR_TITANIA_BD_S6_CUS03_DEMO_BOARD_ATSC_1 0
#endif

#ifndef CONFIG_MSTAR_TITANIA_BD_S6_CUS03_DEMO_BOARD_DVB_1
  #define CONFIG_MSTAR_TITANIA_BD_S6_CUS03_DEMO_BOARD_DVB_1 0
#endif

#ifndef CONFIG_MSTAR_TITANIA_BD_MST055A_D01A_S
  #define CONFIG_MSTAR_TITANIA_BD_MST055A_D01A_S 0
#endif

#ifndef CONFIG_MSTAR_TITANIA_BD_MST055B_D01A_S
  #define CONFIG_MSTAR_TITANIA_BD_MST055B_D01A_S 0
#endif

#ifndef CONFIG_MSTAR_TITANIA_BD_MST055C_D01A_S
  #define CONFIG_MSTAR_TITANIA_BD_MST055C_D01A_S 0
#endif

#ifndef CONFIG_MSTAR_TITANIA_BD_MST055E_D01A_S
  #define CONFIG_MSTAR_TITANIA_BD_MST055E_D01A_S 0
#endif

#ifndef CONFIG_MSTAR_TITANIA_BD_MST056C_D01A_S
  #define CONFIG_MSTAR_TITANIA_BD_MST056C_D01A_S 0
#endif

#ifndef CONFIG_MSTAR_TITANIA_BD_FPGA
  #define CONFIG_MSTAR_TITANIA_BD_FPGA 0
#endif

#ifndef CONFIG_MSTAR_TITANIA_MMAP_32MB
  #define CONFIG_MSTAR_TITANIA_MMAP_32MB 0
#endif

#ifndef CONFIG_MSTAR_TITANIA_MMAP_64MB
  #define CONFIG_MSTAR_TITANIA_MMAP_64MB 0
#endif

#ifndef CONFIG_MSTAR_TITANIA_MMAP_32MB_32MB
  #define CONFIG_MSTAR_TITANIA_MMAP_32MB_32MB 0
#endif

#ifndef CONFIG_MSTAR_TITANIA_MMAP_64MB_32MB
  #define CONFIG_MSTAR_TITANIA_MMAP_64MB_32MB 0
#endif

#ifndef CONFIG_MSTAR_TITANIA_MMAP_64MB_64MB
  #define CONFIG_MSTAR_TITANIA_MMAP_64MB_64MB 0
#endif

#ifndef CONFIG_MSTAR_TITANIA_MMAP_128MB_128MB
  #define CONFIG_MSTAR_TITANIA_MMAP_128MB_128MB 0
#endif

#ifndef CONFIG_MSTAR_TITANIA_MMAP_4MB_FLASH
  #define CONFIG_MSTAR_TITANIA_MMAP_4MB_FLASH 0
#endif

#endif
